extends: eslint:recommended
parserOptions:
    ecmaVersion: 6
    sourceType: module
env:
    browser: true
    commonjs: true
    es6: true
rules:
  accessor-pairs: error
  array-bracket-spacing:
    - error
    - never
  array-callback-return: error
  arrow-body-style: error
  arrow-parens:
    - error
    - always
  arrow-spacing:
    - error
    - after: true
      before: true
  block-scoped-var: error
  block-spacing: error
  brace-style:
    - error
    - 1tbs
  callback-return: error
  camelcase: error
  class-methods-use-this: 'off'
  comma-dangle: error
  comma-spacing:
    - error
    - after: true
      before: false
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: 'off'
  consistent-this: error
  curly: error
  default-case: 'off'
  dot-location:
    - error
    - property
  dot-notation: 'off'
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-name-matching: error
  func-names:
    - error
    - never
  func-style: 'off'
  generator-star-spacing: error
  global-require: error
  guard-for-in: 'off'
  handle-callback-err: error
  id-blacklist: error
  id-length: 'off'
  id-match: error
  indent: error
  init-declarations: 'off'
  jsx-quotes: error
  key-spacing: error
  keyword-spacing:
    - error
    - after: true
      before: true
  line-comment-position: 'off'
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  lines-around-directive: error
  max-depth: error
  max-len: 'off'
  max-lines: 'off'
  max-nested-callbacks: error
  max-params: 'off'
  max-statements: 'off'
  max-statements-per-line: error
  multiline-ternary: 'off'
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: error
  no-alert: error
  no-array-constructor: error
  no-bitwise: 'off'
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-floating-decimal: error
  no-global-assign: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: 'off'
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-operators: error
  no-mixed-requires: error
  no-multi-spaces: error
  no-multi-str: error
  no-multiple-empty-lines: error
  no-negated-condition: 'off'
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign:
    - error
    - props: false
  no-path-concat: error
  no-plusplus: 'off'
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: error
  no-shadow-restricted-names: error
  no-spaced-func: error
  no-sync: error
  no-tabs: error
  no-template-curly-in-string: error
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: error
  no-undef-init: error
  no-undefined: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary:
    - error
    - defaultAssignment: true
  no-unsafe-negation: error
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-var: error
  no-void: error
  no-warning-comments: 'off'
  no-whitespace-before-property: error
  no-with: error
  object-curly-newline: 'off'
  object-curly-spacing: 'off'
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line:
    - error
    - initializations
  operator-assignment:
    - error
    - always
  operator-linebreak: 'off'
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-numeric-literals: error
  prefer-reflect: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: 'off'
  quotes: 'off'
  radix:
    - error
    - as-needed
  require-jsdoc: 'off'
  rest-spread-spacing:
    - error
    - never
  semi: error
  semi-spacing:
    - error
    - after: true
      before: false
  sort-imports: 'off'
  sort-keys: 'off'
  sort-vars: 'off'
  space-before-blocks: error
  space-before-function-paren: error
  space-in-parens: 'off'
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment:
    - error
    - always
  strict: error
  symbol-description: error
  template-curly-spacing:
    - error
    - never
  unicode-bom:
    - error
    - never
  valid-jsdoc: error
  vars-on-top: 'off'
  wrap-iife: error
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
